# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
