# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='awdf'),
            preserve_default=False,
        ),
    ]
