# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM')], help_text='Finish Time', max_length=200, verbose_name='Finish time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM')], help_text='Booking slot', max_length=200, verbose_name='Booking slot'),
        ),
    ]
